<a href="https://colab.research.google.com/github/ernanibn/reconhecimento_padroes_23/blob/main/aula5a_gridsearch_Exercicio_resolvido.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Leitura do dataframe

from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

# Link: https://archive.ics.uci.edu/dataset/551/gas+turbine+co+and+nox+emission+data+set

# url = 'https://drive.google.com/uc?id={}'.format('1W34ureoxGl1qZU5e9VcyDMyOt2Guv2TqwqI8PXMf3G8')
# url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQdfzoyG06RvDNBEvhfClEtmMOPEA4SPo3FByuXBLkBecXeNC9EJIeR1P-yX9gQxz58UGHsI7-DGuUJ/pub?gid=361876694&single=true&output=csv'


url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vR_hpkUuJ33j3vqI7QektxKHFVPZFnFMid71sIyHD19IGA6G2GfBWA_UEqWscvprlQQEd5Hf1-nPDq3/pub?output=csv'
df = pd.read_csv(url)

# pd.to_datetime(df.iloc[:0], format='%d/%m/%Y')

df.iloc[:0] = df.iloc[:0].apply(pd.to_datetime)

# get the locations
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


AT      AP      AH    AFDP    GTEP     TIT     TAT     TEY     CDP  \
0  4.5878  1018.7  83.675  3.5758  23.979  1086.2  549.83  134.67  11.898   
1  4.2932  1018.3  84.235  3.5709  23.951  1086.1  550.05  134.67  11.892   
2  3.9045  1018.4  84.858  3.5828  23.990  1086.5  550.19  135.10  12.042   
3  3.7436  1018.3  85.434  3.5808  23.911  1086.5  550.17  135.03  11.990   
4  3.7516  1017.8  85.182  3.5781  23.917  1085.9  550.00  134.67  11.910   

        CO     NOX  
0  0.32663  81.952  
1  0.44784  82.377  
2  0.45144  83.776  
3  0.23107  82.505  
4  0.26747  82.028

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import cross_validate
from sklearn.model_selection import train_test_split
from sklearn.metrics import make_scorer, mean_squared_error
import numpy as np

# GridSearch dentro do Pipeline com Padronização


parametros = {'n_neighbors' : [3,5,7]
              }

GridSearchKNN = GridSearchCV(KNeighborsRegressor(), parametros,
                      scoring='neg_mean_squared_error')

modelo_com = Pipeline([
    ("padronizacao", StandardScaler()),
    ("gsknn", GridSearchKNN)
])


scores = cross_validate(modelo_com, X, y, cv=5, return_estimator=True,
                        scoring=make_scorer(mean_squared_error
                                            , squared=False
                                            , greater_is_better = False
                                            ))
print(scores['test_score'])
compad = np.mean(scores['test_score'])
print(f"Com padronização: {compad}")



[-6.07954986 -5.71825243 -3.23989794 -4.76781385 -5.77312713]
Com padronização: -5.115728243375096


In [ ]:
# GridSearch dentro do Pipeline sem padronização


parametros = {'n_neighbors' : [3,5,7]}

GridSearchKNN = GridSearchCV(KNeighborsRegressor(), parametros,
                      scoring='neg_mean_squared_error')

modelo_sem = Pipeline([("gsknn", GridSearchKNN)
])


scores = cross_validate(modelo_sem, X, y, cv=5, return_estimator=True,
                        scoring=make_scorer(mean_squared_error, squared=False
                                            , greater_is_better = False))
print(scores['test_score'])
sempad = np.mean(scores['test_score'])
print(f"Sem padronização: {sempad}")



[-6.02236581 -5.4559952  -3.37168706 -3.90302921 -6.08597781]
Sem padronização: -4.967811019788892
[-6.02236581 -5.4559952  -3.37168706 -3.90302921 -6.08597781]
Sem padronização: -4.967811019788892


In [ ]:
# Pipeline dentro do GridSearch com padronização

pipeline = Pipeline([
    ("padronizacao", StandardScaler()),
    ("knn", KNeighborsRegressor())
])

parametros = {'knn__n_neighbors' : [3,5,7]}
modelo = GridSearchCV(pipeline, parametros,
                      scoring='neg_mean_squared_error')


scores = cross_validate(modelo_com, X, y, cv=5, return_estimator=True,
                        scoring=make_scorer(mean_squared_error, squared=False,
                                            greater_is_better = False))
print(scores['test_score'])
compad = np.mean(scores['test_score'])
print(f"Com padronização: {compad}")


[-6.07954986 -5.71825243 -3.23989794 -4.76781385 -5.77312713]
Com padronização: -5.115728243375096
